FISHCAKE_MIGRATIONS_DIR="./"
FISHCAKE_POLYGON_RPC="http://127.0.0.1"
FISHCAKE_HTTP_HOST="127.0.0.1"
FISHCAKE_HTTP_PORT=8080

FISHCAKE_METRICS_HOST="127.0.0.1"
FISHCAKE_METRICS_PORT=8081
FISHCAKE_DB_HOST=8081

FISHCAKE_DB_PORT=8081

FISHCAKE_DB_USER=8081

FISHCAKE_DB_PASSWORD=1111

FISHCAKE_DB_NAME=8081